// login reducer
export const SET_LOGIN_SUCCESS = "SET_LOGIN_SUCCESS";
export const SET_LOGOUT = "SET_LOGOUT";
export const SET_LOGIN_ERROR = "SET_LOGIN_ERROR";

// accountList
export const SET_ACCOUNT_LISTS = "SET_ACCOUNT_LISTS";

// recipient lists
export const GET_RECIPIENT_LISTS = "GET_RECIPIENT_LISTS";
export const SET_ADD_RECIPIENT_SUCCESS = "SET_ADD_RECIPIENT_SUCCESS";
export const SET_ADD_RECIPIENT_FAIL = "SET_ADD_RECIPIENT_FAIL";

// transfer
export const FINAL_TRANSFER = "FINAL_TRANSFER";
export const CANCEL_TRANSFER = "CANCEL_TRANSFER";
export const EXECUTE_TRANSFER_SUCCESS = "EXECUTE_TRANSFER_SUCCESS";
export const EXECUTE_TRANSFER_FAIL = "EXECUTE_TRANSFER_FAIL";
export const SET_ORIGIN_HASH = "SET_ORIGIN_HASH";
export const SET_INFO_TRANSFER = "SET_INFO_TRANSFER";

// history
export const GET_HISTORY_TRANSACTION_SUCCESS = "GET_HISTORY_TRANSACTION";
export const GET_HISTORY_TRANSACTION_FAIL = "GET_HISTORY_TRANSACTION_FAIL";
export const CLEAR_GET_HISTORY = "CLEAR_GET_HISTORY";
